---
title: "exploration"
author: "Qian Leng"
date: "2022/3/30"
output: html_document
---

```{r }
data <- read.csv("data.csv")
```

### Wordcloud for Originating Lender Bank
```{r warning=FALSE}
library(wordcloud)
library(dplyr)
data1 <- data[,c(1,10)]
data1 <- na.omit(data1)
data1 <- data1 %>% group_by(originatinglender) %>% summarize(freq = n())
data1 <- as.data.frame(data1)
data1 <- data1[-1,]

#plot.new()
#text(x=0.5, y=0.5, "Wordcloud for Originating Lender Bank")
wordcloud(words = data1$originatinglender, 
          freq = data1$freq, max.words=100, 
          random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))
```


### Wordcloud for Originating Lender State
```{r warning=FALSE}
data2 <- data[,c(1,11)]
data2 <- na.omit(data2)
data2 <- data2 %>% group_by(originatinglendercity) %>% summarize(freq = n())
data2 <- as.data.frame(data2)
data2 <- data2[-1,]

#plot.new()
#text(x=0.5, y=0.5, "Wordcloud for Originating Lender State")
wordcloud(words = data2$originatinglendercity, 
          freq = data2$freq, max.words=70, 
          random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))
```